/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package cine_tics;


import horarios.asientos;
import horarios.asientos2;
import horarios.asientos1;
import horarios.asientos3;
import horarios.asientos10;
import horarios.asientos11;
import horarios.asientos12;
import horarios.asientos13;
import horarios.asientos14;
import horarios.asientos15;
import horarios.asientos4;
import horarios.asientos5;
import horarios.asientos6;
import horarios.asientos7;
import horarios.asientos8;
import horarios.asientos9;
import java.text.SimpleDateFormat;
import java.util.Date;
import javax.swing.ImageIcon;
import javax.swing.JOptionPane;


/**
 *
 * @author nancy
 */
public final class taquilla extends javax.swing.JFrame {
cartelera c =new cartelera();
String [][]hora=c.getHorarios();
int con=1;
public String peliculas[]= {"Fragmentado", "El Aro 3", "La Bella y la Bestia", "Logan"};
public static String peliculaC;
public static String horario;
public static int lugares;






    /**
     * Creates new form taquilla
     */
    public taquilla() {
        initComponents();
        listarHorario();
        getHorario();
        setDefaultCloseOperation(0);
    
  
        
        
    for (String pelicula : peliculas) {
        jComboBox3.addItem(pelicula);
    }
       
              
    }
    public void listarHorario()
    {
        jComboBox2.removeAllItems();
        SimpleDateFormat formato = new SimpleDateFormat("hh:mm aa");
        Date horario;
        String h;
        try {
            for (String[] hora1 : hora) {
                horario = formato.parse(hora1[con-1]);
                h=formato.format(horario);
                if(horario.after(formato.parse(getHorario())))
                {
                    jComboBox2.addItem(h);
                   // System.out.println(h);
                }
            }
        } catch (Exception e) {
        }
    }
    public String getHorario()
    {
        SimpleDateFormat format = new SimpleDateFormat("hh:mm aa");
        Date horaActual = new Date();
        String horarioConformato = format.format(horaActual);
        return  horarioConformato;
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jComboBox1 = new javax.swing.JComboBox();
        jComboBox2 = new javax.swing.JComboBox();
        jLabel1 = new javax.swing.JLabel();
        jLabel2 = new javax.swing.JLabel();
        jLabel3 = new javax.swing.JLabel();
        jLabel4 = new javax.swing.JLabel();
        jButton1 = new javax.swing.JButton();
        jLabel5 = new javax.swing.JLabel();
        jComboBox3 = new javax.swing.JComboBox();
        imagen = new javax.swing.JLabel();
        jButton2 = new javax.swing.JButton();
        jScrollPane1 = new javax.swing.JScrollPane();
        jTextArea1 = new javax.swing.JTextArea();
        jButton3 = new javax.swing.JButton();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setBackground(new java.awt.Color(153, 102, 255));
        setForeground(java.awt.Color.orange);

        jComboBox1.setEnabled(false);
        jComboBox1.addItemListener(new java.awt.event.ItemListener() {
            public void itemStateChanged(java.awt.event.ItemEvent evt) {
                jComboBox1ItemStateChanged(evt);
            }
        });
        jComboBox1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jComboBox1ActionPerformed(evt);
            }
        });

        jComboBox2.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jComboBox2ActionPerformed(evt);
            }
        });

        jLabel1.setBackground(new java.awt.Color(255, 255, 255));
        jLabel1.setFont(new java.awt.Font("Tw Cen MT", 0, 36)); // NOI18N
        jLabel1.setForeground(new java.awt.Color(0, 0, 102));
        jLabel1.setText("TAQUILLA");

        jLabel2.setBackground(new java.awt.Color(51, 255, 255));
        jLabel2.setFont(new java.awt.Font("Tw Cen MT", 1, 14)); // NOI18N
        jLabel2.setForeground(new java.awt.Color(255, 0, 0));
        jLabel2.setText("CINE TIC'S");

        jLabel3.setFont(new java.awt.Font("Tahoma", 0, 14)); // NOI18N
        jLabel3.setForeground(new java.awt.Color(51, 51, 255));
        jLabel3.setText("SALA");

        jLabel4.setFont(new java.awt.Font("Tahoma", 0, 14)); // NOI18N
        jLabel4.setForeground(new java.awt.Color(0, 51, 255));
        jLabel4.setText("HORARIO");

        jButton1.setFont(new java.awt.Font("Tahoma", 1, 11)); // NOI18N
        jButton1.setIcon(new javax.swing.ImageIcon(getClass().getResource("/img/sillon.png"))); // NOI18N
        jButton1.setText("ELIGE TU LUGAR");
        jButton1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton1ActionPerformed(evt);
            }
        });

        jLabel5.setFont(new java.awt.Font("Tahoma", 0, 14)); // NOI18N
        jLabel5.setForeground(new java.awt.Color(0, 51, 255));
        jLabel5.setText("PELICULA");

        jComboBox3.addItemListener(new java.awt.event.ItemListener() {
            public void itemStateChanged(java.awt.event.ItemEvent evt) {
                jComboBox3ItemStateChanged(evt);
            }
        });
        jComboBox3.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jComboBox3ActionPerformed(evt);
            }
        });

        imagen.setMaximumSize(new java.awt.Dimension(500, 760));

        jButton2.setFont(new java.awt.Font("Tahoma", 1, 11)); // NOI18N
        jButton2.setIcon(new javax.swing.ImageIcon(getClass().getResource("/img/espalda.png"))); // NOI18N
        jButton2.setText("MENÚ PRINCIPAL");
        jButton2.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton2ActionPerformed(evt);
            }
        });

        jTextArea1.setColumns(20);
        jTextArea1.setRows(5);
        jScrollPane1.setViewportView(jTextArea1);

        jButton3.setFont(new java.awt.Font("Tahoma", 1, 11)); // NOI18N
        jButton3.setIcon(new javax.swing.ImageIcon(getClass().getResource("/img/notas.png"))); // NOI18N
        jButton3.setText("COMPRAR");
        jButton3.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton3ActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addContainerGap()
                        .addComponent(jLabel2))
                    .addGroup(layout.createSequentialGroup()
                        .addGap(118, 118, 118)
                        .addComponent(jLabel5))
                    .addGroup(layout.createSequentialGroup()
                        .addGap(118, 118, 118)
                        .addComponent(jLabel4))
                    .addGroup(layout.createSequentialGroup()
                        .addGap(52, 52, 52)
                        .addComponent(jComboBox3, javax.swing.GroupLayout.PREFERRED_SIZE, 206, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(layout.createSequentialGroup()
                        .addGap(135, 135, 135)
                        .addComponent(jLabel3)))
                .addGap(23, 23, 23)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jLabel1, javax.swing.GroupLayout.PREFERRED_SIZE, 202, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addGroup(layout.createSequentialGroup()
                        .addGap(10, 10, 10)
                        .addComponent(imagen, javax.swing.GroupLayout.PREFERRED_SIZE, 244, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 53, Short.MAX_VALUE)
                .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 348, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(21, 21, 21))
            .addGroup(layout.createSequentialGroup()
                .addGap(76, 76, 76)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                    .addComponent(jComboBox2, javax.swing.GroupLayout.PREFERRED_SIZE, 137, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jComboBox1, javax.swing.GroupLayout.PREFERRED_SIZE, 137, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jButton2, javax.swing.GroupLayout.DEFAULT_SIZE, 165, Short.MAX_VALUE)
                    .addComponent(jButton1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addComponent(jButton3)
                .addGap(110, 110, 110))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                            .addGroup(layout.createSequentialGroup()
                                .addComponent(jLabel2)
                                .addGap(13, 13, 13)
                                .addComponent(jLabel5))
                            .addComponent(jLabel1, javax.swing.GroupLayout.PREFERRED_SIZE, 80, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(layout.createSequentialGroup()
                                .addGap(18, 18, 18)
                                .addComponent(jComboBox3, javax.swing.GroupLayout.PREFERRED_SIZE, 39, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addGap(18, 18, 18)
                                .addComponent(jLabel3)
                                .addGap(18, 18, 18)
                                .addComponent(jComboBox1, javax.swing.GroupLayout.PREFERRED_SIZE, 38, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addGap(28, 28, 28)
                                .addComponent(jLabel4, javax.swing.GroupLayout.PREFERRED_SIZE, 17, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addGap(18, 18, 18)
                                .addComponent(jComboBox2, javax.swing.GroupLayout.PREFERRED_SIZE, 35, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addGap(57, 57, 57)
                                .addComponent(jButton1))
                            .addGroup(layout.createSequentialGroup()
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addComponent(imagen, javax.swing.GroupLayout.PREFERRED_SIZE, 356, javax.swing.GroupLayout.PREFERRED_SIZE))))
                    .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 436, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(18, 18, 18)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                    .addComponent(jButton2)
                    .addComponent(jButton3))
                .addContainerGap(27, Short.MAX_VALUE))
        );

        pack();
        setLocationRelativeTo(null);
    }// </editor-fold>//GEN-END:initComponents

    private void jComboBox1ItemStateChanged(java.awt.event.ItemEvent evt) {//GEN-FIRST:event_jComboBox1ItemStateChanged
        // TODO add your handling code here:
    }//GEN-LAST:event_jComboBox1ItemStateChanged

    private void jComboBox2ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jComboBox2ActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_jComboBox2ActionPerformed

    private void jComboBox1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jComboBox1ActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_jComboBox1ActionPerformed

    private void jComboBox3ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jComboBox3ActionPerformed
        // TODO add your handling code here:
        
       
        
        
         int numIndex=jComboBox2.getSelectedIndex();
         int salaIndex=jComboBox3.getSelectedIndex();
          //System.out.println("Index: "+salaIndex);
          String s= ""+numIndex;
          
           //System.out.println(peliculaC);
          
          if(salaIndex == 0){
         jComboBox1.removeAllItems();
         jComboBox1.addItem(1);
     
          this.imagen.setIcon(new ImageIcon("src/img/Fragmentado.jpg"));
        }
        
         if(salaIndex == 1){
         jComboBox1.removeAllItems();
         jComboBox1.addItem(2);
       
         this.imagen.setIcon(new ImageIcon("src/img/aro.jpg"));
        }
        
        if(salaIndex == 2){
         jComboBox1.removeAllItems();
         jComboBox1.addItem(3);
         
         this.imagen.setIcon(new ImageIcon("src/img/ByB.jpg"));
        }
        
         if(salaIndex == 3){
        jComboBox1.removeAllItems();
        jComboBox1.addItem(4);
      
         this.imagen.setIcon(new ImageIcon("src/img/logan.jpg"));
        }
          if(con==4)
       {
          con=0;
      }
       con++;
      //System.out.println("***********");
     con=(int)jComboBox1.getSelectedItem();
            listarHorario();
        
    }//GEN-LAST:event_jComboBox3ActionPerformed

    private void jComboBox3ItemStateChanged(java.awt.event.ItemEvent evt) {//GEN-FIRST:event_jComboBox3ItemStateChanged
        // TODO add your handling code here:
     
          
        
    }//GEN-LAST:event_jComboBox3ItemStateChanged

    private void jButton2ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton2ActionPerformed
        // TODO add your handling code here:
            menu l = new menu();
            l.setVisible(true);
            this.setVisible(false);
    }//GEN-LAST:event_jButton2ActionPerformed

    private void jButton1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton1ActionPerformed
        // TODO add your handling code here:
            
             //this.setVisible(false);
            int salaIndex=jComboBox3.getSelectedIndex();
            peliculaC = (String) jComboBox3.getSelectedItem();
            horario = (String) jComboBox2.getSelectedItem();  
            //jComboBox3.setSelectedItem(salaIndex);
            //System.out.println("Pelicula:"+peliculaC);
            //System.out.println("Horario:"+horario);
            
            
            //Pelicula Fragmentado y horario
            
            if("Fragmentado".equals(peliculaC) && "01:15 PM".equals(horario)){
            asientos l = new asientos();
            l.setVisible(true);
            System.out.println("Frame 1");
            }
            
            if("Fragmentado".equals(peliculaC) && "02:30 PM".equals(horario)){
            asientos1 l = new asientos1();
            l.setVisible(true);
            System.out.println("Frame 2");
            }
            
            if("Fragmentado".equals(peliculaC) && "04:40 PM".equals(horario)){
            asientos2 l = new asientos2();
            l.setVisible(true);
            System.out.println("Frame 3");
            }
            
            if("Fragmentado".equals(peliculaC) && "10:30 PM".equals(horario)){
            asientos3 l = new asientos3();
            l.setVisible(true);
            System.out.println("Frame 4");
            }
            
            //Pelicula El ARO 3 y horario
            
            if("El Aro 3".equals(peliculaC) && "02:50 PM".equals(horario)){
            asientos4 l = new asientos4();
            l.setVisible(true);
            System.out.println("Frame 5");
            }
            
            if("El Aro 3".equals(peliculaC) && "06:10 PM".equals(horario)){
            asientos5 l = new asientos5();
            l.setVisible(true);
            System.out.println("Frame 6");
            }
            
            if("El Aro 3".equals(peliculaC) && "07:50 PM".equals(horario)){
            asientos6 l = new asientos6();
            l.setVisible(true);
            System.out.println("Frame 7");
            }
            
            if("El Aro 3".equals(peliculaC) && "09:30 PM".equals(horario)){
            asientos7 l = new asientos7();
            l.setVisible(true);
            System.out.println("Frame 8");
            }
            
             //Pelicula La bella y la bestia y horario
            
            if("La Bella y la Bestia".equals(peliculaC) && "03:20 PM".equals(horario)){
            asientos8 l = new asientos8();
            l.setVisible(true);
            System.out.println("Frame 9");
            }
            
            if("La Bella y la Bestia".equals(peliculaC) && "04:30 PM".equals(horario)){
            asientos9 l = new asientos9();
            l.setVisible(true);
            System.out.println("Frame 10");
            }
            
            if("La Bella y la Bestia".equals(peliculaC) && "05:10 PM".equals(horario)){
            asientos10 l = new asientos10();
            l.setVisible(true);
            System.out.println("Frame 11");
            }
            
            if("La Bella y la Bestia".equals(peliculaC) && "07:10 PM".equals(horario)){
            asientos11 l = new asientos11();
            l.setVisible(true);
            System.out.println("Frame 12");
            }
            
             //Pelicula Logan y horario
            
            if("Logan".equals(peliculaC) && "01:50 PM".equals(horario)){
            asientos12 l = new asientos12();
            l.setVisible(true);
            System.out.println("Frame 13");
            }
            
            if("Logan".equals(peliculaC) && "03:20 PM".equals(horario)){
            asientos13 l = new asientos13();
            l.setVisible(true);
            System.out.println("Frame 14");
            }
            
            if("Logan".equals(peliculaC) && "08:10 PM".equals(horario)){
            asientos14 l = new asientos14();
            l.setVisible(true);
            System.out.println("Frame 15");
            }
            
            if("Logan".equals(peliculaC) && "09:00 PM".equals(horario)){
            asientos15 l = new asientos15();
            l.setVisible(true);
            System.out.println("Frame 16");
            }
    }//GEN-LAST:event_jButton1ActionPerformed

    private void jButton3ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton3ActionPerformed
        // TODO add your handling code here:
        imprimir_ticket();
        
    }//GEN-LAST:event_jButton3ActionPerformed

    
    public String getNamePelicula()
{

    return peliculaC;
} 
    
    public String imprimir_ticket(){
        
     asientos a = new asientos();
     asientos1 b = new asientos1();
     asientos2 c = new asientos2();
     asientos3 d = new asientos3();
     
     asientos4 e = new asientos4();
     asientos5 f = new asientos5();
     asientos6 g = new asientos6();
     asientos7 h = new asientos7();
     
     asientos8 i = new asientos8();
     asientos9 j = new asientos9();
     asientos10 k = new asientos10();
     asientos11 l = new asientos11();
     
     asientos12 m = new asientos12();
     asientos13 n = new asientos13();
     asientos14 o = new asientos14();
     asientos15 p = new asientos15();
     
    
     float subTotal = 0;
     float iva = 0;
     float total = 0;
   
     int lugares = a.getLugares()+b.getLugares()+c.getLugares()+d.getLugares()
                  +e.getLugares()+f.getLugares()+g.getLugares()+h.getLugares()
                  +i.getLugares()+j.getLugares()+k.getLugares()+l.getLugares()
                  +m.getLugares()+n.getLugares()+o.getLugares()+p.getLugares();
   
     
      subTotal = 45 * lugares;
      iva = 0.16f * subTotal;
      total = subTotal + iva;
        
        System.out.println("Metodo de imprimir");
        peliculaC = (String) jComboBox3.getSelectedItem();
        horario = (String) jComboBox2.getSelectedItem();
        if(horario != null){
        jTextArea1.setText("***********TICKET DE COMPRA***********\n \n *************CONCEPTOS*********** \n"+"PELICULA: "+peliculaC+"\nSALA: "+con+"\nLUGARES: "+lugares+"\nHORARIO: "+horario+"\n ******************************* \n "+"SUBTOTAL: $"+Float.toString(subTotal)+"\n IVA: $"+Float.toString(iva)+"\n TOTAL: $"+Float.toString(total)+"\n \n *********GRACIAS POR SU COMPRA********");
        a.setLugares(0);
        b.setLugares(0);
        c.setLugares(0);
        d.setLugares(0);
        e.setLugares(0);
        f.setLugares(0);
        g.setLugares(0);
        h.setLugares(0);
        i.setLugares(0);
        j.setLugares(0);
        k.setLugares(0);
        l.setLugares(0);
        m.setLugares(0);
        n.setLugares(0);
        o.setLugares(0);
        p.setLugares(0);
        }else{
            JOptionPane.showMessageDialog(null, "Función no disponible");
            
        } 
        
        
    return null;
    
    }

    /**
     * @param args the command line arguments
     */
   

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JLabel imagen;
    private javax.swing.JButton jButton1;
    private javax.swing.JButton jButton2;
    private javax.swing.JButton jButton3;
    private javax.swing.JComboBox jComboBox1;
    private javax.swing.JComboBox jComboBox2;
    public javax.swing.JComboBox jComboBox3;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JTextArea jTextArea1;
    // End of variables declaration//GEN-END:variables
}
